sonar.projectKey=Portifolio
sonar.projectName=Portifolio
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=sqp_e1d6eb122fee28a3f83042893fb4d4eb4736da65

# 1. Remova os testes daqui e deixe apenas o node_modules
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**, .vite/**  

# 2. Indique explicitamente onde estão os testes
sonar.tests=.
sonar.test.inclusions=**/*.test.jsx, **/*.test.js

# 3. Mantenha o caminho do relatório
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Suas regras de ignore (mantenha como estão)
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=react:prop-types
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.jsx